/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import {CuboidCollider } from '@react-three/rapier'
import {a } from '@react-spring/three'
import fairy from '../assets/3d/PortfolioFairyThreeJSReady2.glb';
import { pressurePlateActivated } from "../pages/Home";
import * as THREE from 'three';

const Fairy = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(fairy);
  const { actions } = useAnimations(animations, group);

  const [pressurePlateActivated, setPressurePlateActivated] = useState(null);
  
 

  useEffect(()=>{
      
    
      if(pressurePlateActivated){
       
        actions['wave'].setLoop(THREE.LoopOnce);
        actions['wave'].play();
          // You can listen to the finished event and stop the animation there
        

      }else{
        actions['wave'].reset();
        actions['idle'].play();
      }

      console.log("Start wave animation: " + pressurePlateActivated)
  }, [pressurePlateActivated])

  function Wave(){
   
    setPressurePlateActivated(true);
    
  }


  function StopWave(){
    setPressurePlateActivated(false);

  }
  return (

    <a.group ref={group} {...props} dispose={null}>

       {/* pressure plate to activate wave animation */}
       <CuboidCollider
            position={[-25, 10, 17]}
            args={[2, 2, 2]}
            sensor
            onIntersectionEnter={() => Wave()}
            onIntersectionExit={() => StopWave()}
        />


      <group name="Scene">
        <group name="metarig">
          <primitive object={nodes.spine} />
        </group>
        <group name="rig">
          <group name="Cube">
            <skinnedMesh
              name="Cube_1"
              geometry={nodes.Cube_1.geometry}
              material={materials.face}
              skeleton={nodes.Cube_1.skeleton}
            />
            <skinnedMesh
              name="Cube_2"
              geometry={nodes.Cube_2.geometry}
              material={materials["Material.001"]}
              skeleton={nodes.Cube_2.skeleton}
            />
            <skinnedMesh
              name="Cube_3"
              geometry={nodes.Cube_3.geometry}
              material={materials.eyebrow}
              skeleton={nodes.Cube_3.skeleton}
            />
            <skinnedMesh
              name="Cube_4"
              geometry={nodes.Cube_4.geometry}
              material={materials.eyelashes}
              skeleton={nodes.Cube_4.skeleton}
            />
            <skinnedMesh
              name="Cube_5"
              geometry={nodes.Cube_5.geometry}
              material={materials.skin}
              skeleton={nodes.Cube_5.skeleton}
            />
            <skinnedMesh
              name="Cube_6"
              geometry={nodes.Cube_6.geometry}
              material={materials.hair}
              skeleton={nodes.Cube_6.skeleton}
            />
          </group>
          <skinnedMesh
            name="Cube003"
            geometry={nodes.Cube003.geometry}
            material={materials.fairyDress3}
            skeleton={nodes.Cube003.skeleton}
          />
          <skinnedMesh
            name="Cube005"
            geometry={nodes.Cube005.geometry}
            material={materials.skin}
            skeleton={nodes.Cube005.skeleton}
          />
          <group name="Cube006">
            <skinnedMesh
              name="Cube006_1"
              geometry={nodes.Cube006_1.geometry}
              material={materials.FairyDress}
              skeleton={nodes.Cube006_1.skeleton}
            />
            <skinnedMesh
              name="Cube006_2"
              geometry={nodes.Cube006_2.geometry}
              material={materials.fairyDress2}
              skeleton={nodes.Cube006_2.skeleton}
            />
          </group>
          <group name="Cube007">
            <skinnedMesh
              name="Cube007_1"
              geometry={nodes.Cube007_1.geometry}
              material={materials.eyebrow}
              skeleton={nodes.Cube007_1.skeleton}
            />
            <skinnedMesh
              name="Cube007_2"
              geometry={nodes.Cube007_2.geometry}
              material={materials.diamond}
              skeleton={nodes.Cube007_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="Cube010"
            geometry={nodes.Cube010.geometry}
            material={materials.skin}
            skeleton={nodes.Cube010.skeleton}
          />
          <group name="Cube011">
            <skinnedMesh
              name="Cube011_1"
              geometry={nodes.Cube011_1.geometry}
              material={materials.fairyDress3}
              skeleton={nodes.Cube011_1.skeleton}
            />
            <skinnedMesh
              name="Cube011_2"
              geometry={nodes.Cube011_2.geometry}
              material={materials.diamond}
              skeleton={nodes.Cube011_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="Cube013"
            geometry={nodes.Cube013.geometry}
            material={materials.skin}
            skeleton={nodes.Cube013.skeleton}
          />
          <primitive object={nodes.root} />
          <primitive object={nodes["MCH-torsoparent"]} />
          <primitive object={nodes["MCH-hand_ikparentL"]} />
          <primitive object={nodes["MCH-upper_arm_ik_targetparentL"]} />
          <primitive object={nodes["MCH-hand_ikparentR"]} />
          <primitive object={nodes["MCH-upper_arm_ik_targetparentR"]} />
          <primitive object={nodes["MCH-foot_ikparentL"]} />
          <primitive object={nodes["MCH-thigh_ik_targetparentL"]} />
          <primitive object={nodes["MCH-foot_ikparentR"]} />
          <primitive object={nodes["MCH-thigh_ik_targetparentR"]} />
        </group>
        <group
          name="WGT-rig_spine_fk"
          position={[0, 2.01, -0.87]}
          rotation={[1.745, 0, 0]}
          scale={0.397}
        />
        <group
          name="WGT-rig_spine_fk001"
          position={[0, 2.287, -0.84]}
          rotation={[1.68, 0, 0]}
          scale={0.278}
        />
        <group
          name="WGT-rig_spine_fk002"
          position={[0, 2.287, -0.84]}
          rotation={[1.544, 0, 0]}
          scale={0.37}
        />
        <group
          name="WGT-rig_spine_fk003"
          position={[0, 2.657, -0.85]}
          rotation={[1.537, 0, 0]}
          scale={0.291}
        />
        <group
          name="WGT-rig_tweak_spine"
          position={[0, 1.619, -0.939]}
          rotation={[1.745, 0, 0]}
          scale={0.199}
        />
        <group
          name="WGT-rig_tweak_spine001"
          position={[0, 2.01, -0.87]}
          rotation={[1.68, 0, 0]}
          scale={0.139}
        />
        <group
          name="WGT-rig_tweak_spine002"
          position={[0, 2.287, -0.84]}
          rotation={[1.544, 0, 0]}
          scale={0.185}
        />
        <group
          name="WGT-rig_tweak_spine003"
          position={[0, 2.657, -0.85]}
          rotation={[1.537, 0, 0]}
          scale={0.146}
        />
        <group
          name="WGT-rig_tweak_spine004"
          position={[0, 2.947, -0.86]}
          rotation={[2.003, 0, 0]}
          scale={0.053}
        />
        <group
          name="WGT-rig_torso"
          position={[0, 1.814, -0.904]}
          scale={0.802}
        />
        <group
          name="WGT-rig_hips"
          position={[0, 1.619, -0.939]}
          rotation={[1.745, 0, 0]}
          scale={0.334}
        />
        <group
          name="WGT-rig_chest"
          position={[0, 2.657, -0.85]}
          rotation={[1.537, 0, 0]}
          scale={0.446}
        />
        <group
          name="WGT-rig_breastL"
          position={[0.488, 2.341, -0.927]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.252}
        />
        <group
          name="WGT-rig_breastR"
          position={[-0.488, 2.341, -0.927]}
          rotation={[0, 0, Math.PI]}
          scale={-0.252}
        />
        <group
          name="WGT-rig_shoulderL"
          position={[0.033, 2.837, -0.715]}
          rotation={[0.526, -1.229, 0.495]}
          scale={0.557}
        />
        <group
          name="WGT-rig_upper_arm_parentL"
          position={[0.627, 2.935, -0.887]}
          rotation={[-1.245, -1.281, -1.769]}
          scale={0.107}
        />
        <group
          name="WGT-rig_upper_arm_fkL"
          position={[0.627, 2.935, -0.887]}
          rotation={[-1.245, -1.281, -1.769]}
          scale={0.426}
        />
        <group
          name="WGT-rig_forearm_fkL"
          position={[1.036, 2.82, -0.926]}
          rotation={[-1.543, -1.451, -2.063]}
          scale={0.537}
        />
        <group
          name="WGT-rig_hand_fkL"
          position={[1.569, 2.756, -0.928]}
          rotation={[2.194, -1.399, 1.686]}
          scale={0.145}
        />
        <group
          name="WGT-rig_upper_arm_ikL"
          position={[0.627, 2.935, -0.887]}
          rotation={[-1.245, -1.281, -1.769]}
          scale={0.426}
        />
        <group
          name="WGT-rig_upper_arm_ik_targetL"
          position={[0.86, 2.005, -1.401]}
          rotation={[2.098, -0.184, 0.319]}
          scale={0.12}
        />
        <group
          name="WGT-rig_hand_ikL"
          position={[1.569, 2.756, -0.928]}
          rotation={[2.194, -1.399, 1.686]}
          scale={0.145}
        />
        <group
          name="WGT-rig_VIS_upper_arm_ik_poleL"
          position={[1.036, 2.82, -0.926]}
          rotation={[Math.PI / 2, 0, -0.639]}
          scale={0.96}
        />
        <group
          name="WGT-rig_upper_arm_tweakL"
          position={[0.627, 2.935, -0.887]}
          rotation={[-1.245, -1.281, -1.769]}
          scale={0.107}
        />
        <group
          name="WGT-rig_upper_arm_tweakL001"
          position={[0.832, 2.878, -0.907]}
          rotation={[-1.245, -1.281, -1.769]}
          scale={0.107}
        />
        <group
          name="WGT-rig_forearm_tweakL"
          position={[1.036, 2.82, -0.926]}
          rotation={[-1.543, -1.451, -2.063]}
          scale={0.134}
        />
        <group
          name="WGT-rig_forearm_tweakL001"
          position={[1.303, 2.788, -0.927]}
          rotation={[-1.543, -1.451, -2.063]}
          scale={0.134}
        />
        <group
          name="WGT-rig_hand_tweakL"
          position={[1.569, 2.756, -0.928]}
          rotation={[2.194, -1.399, 1.686]}
          scale={0.036}
        />
        <group
          name="WGT-rig_shoulderR"
          position={[-0.033, 2.837, -0.715]}
          rotation={[-2.615, -1.229, 0.495]}
          scale={-0.557}
        />
        <group
          name="WGT-rig_upper_arm_parentR"
          position={[-0.627, 2.935, -0.887]}
          rotation={[1.897, -1.281, -1.769]}
          scale={-0.107}
        />
        <group
          name="WGT-rig_upper_arm_fkR"
          position={[-0.627, 2.935, -0.887]}
          rotation={[1.897, -1.281, -1.769]}
          scale={-0.426}
        />
        <group
          name="WGT-rig_forearm_fkR"
          position={[-1.036, 2.82, -0.926]}
          rotation={[1.598, -1.451, -2.063]}
          scale={-0.537}
        />
        <group
          name="WGT-rig_hand_fkR"
          position={[-1.569, 2.756, -0.928]}
          rotation={[-0.947, -1.399, 1.686]}
          scale={-0.145}
        />
        <group
          name="WGT-rig_upper_arm_ikR"
          position={[-0.627, 2.935, -0.887]}
          rotation={[1.897, -1.281, -1.769]}
          scale={-0.426}
        />
        <group
          name="WGT-rig_upper_arm_ik_targetR"
          position={[-0.86, 2.005, -1.401]}
          rotation={[-1.044, -0.184, 0.319]}
          scale={-0.12}
        />
        <group
          name="WGT-rig_hand_ikR"
          position={[-1.569, 2.756, -0.928]}
          rotation={[-0.947, -1.399, 1.686]}
          scale={-0.145}
        />
        <group
          name="WGT-rig_VIS_upper_arm_ik_poleR"
          position={[-1.036, 2.82, -0.926]}
          rotation={[-Math.PI / 2, 0, -0.639]}
          scale={-0.96}
        />
        <group
          name="WGT-rig_upper_arm_tweakR"
          position={[-0.627, 2.935, -0.887]}
          rotation={[1.897, -1.281, -1.769]}
          scale={-0.107}
        />
        <group
          name="WGT-rig_upper_arm_tweakR001"
          position={[-0.832, 2.878, -0.907]}
          rotation={[1.897, -1.281, -1.769]}
          scale={-0.107}
        />
        <group
          name="WGT-rig_forearm_tweakR"
          position={[-1.036, 2.82, -0.926]}
          rotation={[1.598, -1.451, -2.063]}
          scale={-0.134}
        />
        <group
          name="WGT-rig_forearm_tweakR001"
          position={[-1.303, 2.788, -0.927]}
          rotation={[1.598, -1.451, -2.063]}
          scale={-0.134}
        />
        <group
          name="WGT-rig_hand_tweakR"
          position={[-1.569, 2.756, -0.928]}
          rotation={[-0.947, -1.399, 1.686]}
          scale={-0.036}
        />
        <group
          name="WGT-rig_neck"
          position={[0, 2.947, -0.86]}
          rotation={[2.03, 0, 0]}
          scale={0.148}
        />
        <group
          name="WGT-rig_head"
          position={[0, 3.08, -0.794]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.73}
        />
        <group
          name="WGT-rig_tweak_spine005"
          position={[0, 3.043, -0.815]}
          rotation={[2.099, 0, 0]}
          scale={0.021}
        />
        <group
          name="WGT-rig_thigh_parentL"
          position={[0.48, 1.659, -0.861]}
          rotation={[-1.676, 0.044, 0.074]}
          scale={0.177}
        />
        <group
          name="WGT-rig_thigh_fkL"
          position={[0.48, 1.659, -0.861]}
          rotation={[-1.676, 0.044, 0.074]}
          scale={0.708}
        />
        <group
          name="WGT-rig_shin_fkL"
          position={[0.449, 0.956, -0.787]}
          rotation={[-1.462, 0.059, 0.063]}
          scale={0.75}
        />
        <group
          name="WGT-rig_foot_fkL"
          position={[0.405, 0.211, -0.868]}
          rotation={[-2.673, 0, 0]}
          scale={0.275}
        />
        <group
          name="WGT-rig_toe_fkL"
          position={[0.405, 0.087, -0.623]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.185}
        />
        <group
          name="WGT-rig_thigh_ikL"
          position={[0.48, 1.659, -0.861]}
          rotation={[-1.676, 0.044, 0.074]}
          scale={0.708}
        />
        <group
          name="WGT-rig_thigh_ik_targetL"
          position={[0.549, 0.944, 0.659]}
          rotation={[0.008, 0.069, 0]}
          scale={0.181}
        />
        <group
          name="WGT-rig_foot_ikL"
          position={[0.405, 0.211, -0.868]}
          scale={0.275}
        />
        <group
          name="WGT-rig_VIS_thigh_ik_poleL"
          position={[0.449, 0.956, -0.787]}
          rotation={[Math.PI / 2, 0, 0.011]}
          scale={1.45}
        />
        <group
          name="WGT-rig_thigh_tweakL"
          position={[0.48, 1.659, -0.861]}
          rotation={[-1.676, 0.044, 0.074]}
          scale={0.177}
        />
        <group
          name="WGT-rig_thigh_tweakL001"
          position={[0.464, 1.307, -0.824]}
          rotation={[-1.676, 0.044, 0.074]}
          scale={0.177}
        />
        <group
          name="WGT-rig_shin_tweakL"
          position={[0.449, 0.956, -0.787]}
          rotation={[-1.462, 0.059, 0.063]}
          scale={0.188}
        />
        <group
          name="WGT-rig_shin_tweakL001"
          position={[0.427, 0.583, -0.828]}
          rotation={[-1.462, 0.059, 0.063]}
          scale={0.188}
        />
        <group
          name="WGT-rig_foot_tweakL"
          position={[0.405, 0.211, -0.868]}
          rotation={[-2.673, 0, 0]}
          scale={0.069}
        />
        <group
          name="WGT-rig_foot_spin_ikL"
          position={[0.405, 0.087, -0.623]}
          scale={0.137}
        />
        <group
          name="WGT-rig_foot_heel_ikL"
          position={[0.405, 0.211, -0.868]}
          scale={0.137}
        />
        <group
          name="WGT-rig_toe_ikL"
          position={[0.405, 0.087, -0.623]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.185}
        />
        <group
          name="WGT-rig_thigh_parentR"
          position={[-0.48, 1.659, -0.861]}
          rotation={[1.466, 0.044, 0.074]}
          scale={-0.177}
        />
        <group
          name="WGT-rig_thigh_fkR"
          position={[-0.48, 1.659, -0.861]}
          rotation={[1.466, 0.044, 0.074]}
          scale={-0.708}
        />
        <group
          name="WGT-rig_shin_fkR"
          position={[-0.449, 0.956, -0.787]}
          rotation={[1.679, 0.059, 0.063]}
          scale={-0.75}
        />
        <group
          name="WGT-rig_foot_fkR"
          position={[-0.405, 0.211, -0.868]}
          rotation={[0.469, 0, 0]}
          scale={-0.275}
        />
        <group
          name="WGT-rig_toe_fkR"
          position={[-0.405, 0.087, -0.623]}
          rotation={[0, 0, -Math.PI]}
          scale={-0.185}
        />
        <group
          name="WGT-rig_thigh_ikR"
          position={[-0.48, 1.659, -0.861]}
          rotation={[1.466, 0.044, 0.074]}
          scale={-0.708}
        />
        <group
          name="WGT-rig_thigh_ik_targetR"
          position={[-0.549, 0.944, 0.659]}
          rotation={[-3.133, 0.069, 0]}
          scale={-0.181}
        />
        <group
          name="WGT-rig_foot_ikR"
          position={[-0.405, 0.211, -0.868]}
          rotation={[-Math.PI, 0, 0]}
          scale={-0.275}
        />
        <group
          name="WGT-rig_VIS_thigh_ik_poleR"
          position={[-0.449, 0.956, -0.787]}
          rotation={[-Math.PI / 2, 0, 0.011]}
          scale={-1.45}
        />
        <group
          name="WGT-rig_thigh_tweakR"
          position={[-0.48, 1.659, -0.861]}
          rotation={[1.466, 0.044, 0.074]}
          scale={-0.177}
        />
        <group
          name="WGT-rig_thigh_tweakR001"
          position={[-0.464, 1.307, -0.824]}
          rotation={[1.466, 0.044, 0.074]}
          scale={-0.177}
        />
        <group
          name="WGT-rig_shin_tweakR"
          position={[-0.449, 0.956, -0.787]}
          rotation={[1.679, 0.059, 0.063]}
          scale={-0.188}
        />
        <group
          name="WGT-rig_shin_tweakR001"
          position={[-0.427, 0.583, -0.828]}
          rotation={[1.679, 0.059, 0.063]}
          scale={-0.188}
        />
        <group
          name="WGT-rig_foot_tweakR"
          position={[-0.405, 0.211, -0.868]}
          rotation={[0.469, 0, 0]}
          scale={-0.069}
        />
        <group
          name="WGT-rig_foot_spin_ikR"
          position={[-0.405, 0.087, -0.623]}
          rotation={[-Math.PI, 0, 0]}
          scale={-0.137}
        />
        <group
          name="WGT-rig_foot_heel_ikR"
          position={[-0.405, 0.211, -0.868]}
          rotation={[-Math.PI, 0, 0]}
          scale={-0.137}
        />
        <group
          name="WGT-rig_toe_ikR"
          position={[-0.405, 0.087, -0.623]}
          rotation={[0, 0, -Math.PI]}
          scale={-0.185}
        />
        <group name="WGT-rig_root" scale={4.007} />
      </group>
    </a.group>
  );
}

useGLTF.preload("/PortfolioFairyThreeJSReady2.glb");

export default Fairy;