/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import {a } from '@react-spring/three'
import scene from "../assets/3d/worldThreeJSReadyNoCompression.glb";
import { RigidBody } from "@react-three/rapier";

const World = (props) => {

  const worldRef = useRef();

  const { nodes, materials } = useGLTF(scene);
  
  return (

    <a.group {...props} dispose={null}>


    <mesh geometry={nodes.tiles.geometry} material={materials.stone} />
    <mesh geometry={nodes.branch.geometry} material={materials.land} />
    <mesh geometry={nodes.water.geometry} material={materials.water} />
    <mesh geometry={nodes.Bucket.geometry} material={materials.metal} />
    <mesh geometry={nodes.log.geometry} material={materials.land} />
    <mesh geometry={nodes.rocks.geometry} material={materials.stone} />

    <RigidBody colliders="trimesh" type="fixed">
    <mesh
      geometry={nodes.floatingPlatform.geometry}
      material={materials.grassColor}
    />

    </RigidBody>
    



    <mesh geometry={nodes.fence3.geometry} material={materials.land} />
    <mesh geometry={nodes.fence2.geometry} material={materials.land} />
    <mesh geometry={nodes.fence1.geometry} material={materials.land} />
    <mesh geometry={nodes.table.geometry} material={materials.land} />
    <mesh geometry={nodes.guitar.geometry} material={materials.guitar} />
    
    
    <RigidBody colliders="trimesh" type="fixed" >
      <mesh
        visible = {true}
        geometry={nodes.transparentWall.geometry}
        material={nodes.transparentWall.material}
      />
    </RigidBody>
  

    <mesh
      geometry={nodes.Plane011.geometry}
      material={materials.grassColor}
    />
     
    <mesh
      geometry={nodes.Plane011_1.geometry}
      material={materials.treeLeaves}
    />
    <mesh geometry={nodes.Cylinder009.geometry} material={materials.metal} />
    <mesh
      geometry={nodes.Cylinder009_1.geometry}
      material={materials.barrelBody}
    />
    <mesh geometry={nodes.rock020.geometry} material={materials.treeLeaves} />
    <mesh
      geometry={nodes.rock020_1.geometry}
      material={materials.barrelBody}
    />

    <mesh geometry={nodes.Cube006.geometry} material={materials.land} />

    

    <mesh geometry={nodes.Cube006_1.geometry} material={materials.white} />
    <mesh
      geometry={nodes.Cube006_2.geometry}
      material={materials.standardRed}
    />

    <mesh geometry={nodes.BezierCurve.geometry} material={materials.stone} />

    
    <RigidBody colliders="trimesh" type="fixed">
      <mesh geometry={nodes.BezierCurve_1.geometry} material={materials.land} />
    </RigidBody>
    
    
    <mesh geometry={nodes.Plane020.geometry} material={materials.stone} />
    <mesh
      geometry={nodes.Plane020_1.geometry}
      material={materials.houseWood}
    />
    <mesh geometry={nodes.Plane020_2.geometry} material={materials.land} />
    
   

    
<RigidBody colliders="cuboid" type="fixed" friction={2}>
<mesh
      geometry={nodes.Plane020_3.geometry}
      material={materials.grassColor}
    />
      </RigidBody>




    <mesh
      geometry={nodes.Plane020_4.geometry}
      material={materials.houseWall}
    />
    <mesh geometry={nodes.Plane020_5.geometry} material={materials.roof} />
    <mesh
      geometry={nodes.Plane020_6.geometry}
      material={materials.lightSource}
    />
    <mesh
      geometry={nodes.Plane020_7.geometry}
      material={materials.darkHouseWood}
    />
    <mesh geometry={nodes.Plane020_8.geometry} material={materials.chimney} />
    <mesh geometry={nodes.Plane020_9.geometry} material={materials.metal} />
    <mesh
      geometry={nodes.Plane020_10.geometry}
      material={materials.redTile2}
    />
    <mesh
      geometry={nodes.Plane020_11.geometry}
      material={materials.standardRed}
    />
    <mesh
      geometry={nodes.Plane020_12.geometry}
      material={materials.redTile1}
    />
    <mesh geometry={nodes.Plane005.geometry} material={materials.stone} />
    <mesh geometry={nodes.Plane005_1.geometry} material={materials.white} />
    <mesh geometry={nodes.Plane005_2.geometry} material={materials.water} />
    <mesh
      geometry={nodes.Cube004.geometry}
      material={materials.darkHouseWood}
    />
    <mesh
      geometry={nodes.Cube004_1.geometry}
      material={materials.lightSource}
    />

    

    <mesh geometry={nodes.Cube004_2.geometry} material={materials.metal} />
    <mesh geometry={nodes.Cube004_3.geometry} material={materials.land} />
    <mesh geometry={nodes.Cube004_4.geometry} material={materials.chimney} />
    
  </a.group>



  );
}

useGLTF.preload("/worldThreeJSReadyNoCompression.glb");


export default World;